typography_spectrum: 0.77101
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.843198282411322
  rhythmicContrast: 0.7374868176411837
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24982
analytics:
  google: null
  facebook: null
  twitter: null
name: RevTwo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Reverso.Z
description: Overtuig(en)d in Vastgoed
purpose: []
